name: CI
on: [pull_request]

env:
  JSONNET_VERSION: '0.20.0'
  JSONNET_BUNDLER_VERSION: '0.5.1'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install jsonnet
        run: |
          wget -qO- https://github.com/google/go-jsonnet/releases/download/v${JSONNET_VERSION}/go-jsonnet_${JSONNET_VERSION}_Linux_x86_64.tar.gz \
            | tar -xvz --one-top-level=$HOME/.local/bin

      - name: Install jsonnet-bundler
        run: |
          wget -qO "$HOME/.local/bin/jb" https://github.com/jsonnet-bundler/jsonnet-bundler/releases/download/v${JSONNET_BUNDLER_VERSION}/jb-linux-amd64
          chmod u+x "$HOME/.local/bin/jb"

      - name: Run tests
        run: make test
